{% set name = "quak" %}
{% set version = "0.3.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/quak-{{ version }}.tar.gz
  sha256: fe9e0fad316f3833e01f7bce04d6ea1bc1d80c9830e6532c932672e22ecf8e4a

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=64
    - hatchling
    - pip
  run:
    - python >={{ python_min }}
    - anywidget >=0.9.0
    - python-duckdb >=1.0.0
    - pyarrow >=16.0.0

test:
  imports:
    - quak
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/manzt/quak
  summary: A scalable data profiler for quickly scanning large tables, capturing interactions as executable SQL queries
  description: A scalable data profiler for quickly scanning large tables, capturing interactions as executable SQL queries
  license: MIT
  license_file: LICENSE
  dev_url: https://github.com/manzt/quak

extra:
  recipe-maintainers:
    - giswqs
